version: 0.2
env:
  variables:
    CI: "true"
    LT_USERNAME: "sahiltestrig"
    LT_ACCESS_KEY: "VvPHBy0wUIn975bHAM4Kqtg9MIFFtJKUtScQ3wllleQIr6UKnV"
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - TAG="$( echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8 )"
      - npm install -g
      - ls
  build:
    commands:
      - npm run cy:run
      
