version: 0.2
env:
  variables:
    CI: "true"
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - TAG="$( echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8 )"
      - npm install
  build:
    commands:
      - yarn install
      - yarn cy:run

