version: 0.2
env:
  variables:
    CI: "true"
phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - TAG="$( echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8 )"
      - npm install
  build:
    commands:
      - curl --connect-timeout 3 -f -LI https://dev.clippd.com -o /dev/null -s
      - npm run cy:run
